<div class="markdown-google-sans">
  <h1>INTRODUÇÃO À CIÊNCIA DE DADOS E APRENDIZADO DE MÁQUINAS</h1>
</div>

*Material desenvolvido para a disciplina LOB1266 - Introdução à Ciência de Dados e Aprendizado de Máquinas da Escola de Engenharia de Lorena, Universidade de São Paulo.*

Prof. Dr. Fabiano Fernandes Bargos

Bolsistas: João Vitor Fernandes Gomes (Graduando em Engenharia Química)  
Projeto: `APRIMORAMENTO DE CONTEÚDOS DIDÁTICOS DA DISCIPLINA LOB1266 - INTRODUÇÃO À CIÊNCIA DE DADOS E APRENDIZADO DE MÁQUINAS

# Bibliotecas

Para esta aula, vamos usar de `Pandas`:

In [ ]:
import pandas as pd

---

# Requests

A biblioteca `requests` é utilizada para fazer pedidos no protocolo HTTP e HTTPS, assim como outras ferramentes de autenticação, incluindo os pedidos comuns de GET, POST e outros.  
Como ela já vem instalada no sistema Colab, só é necessário importar:

In [ ]:
import requests

O uso mais básico de requests é pelo método `requests.get(url)`:

In [ ]:
url = 'https://www.eel.usp.br/ensino/graduacao/cursos' # Define o url a ser usado
response = requests.get(url) # Usa requests para pegar o conteúdo da página
response # Mostra a resposta

Um output de `<Response [200]>` corresponde a um OK, e que o pedido retornou o esperado. Caso ocorra outra resposta, como um 403, 404, comumente indica erro:

In [ ]:
url_inexistente = 'https://www.eel.usp.br/ensino/bombas_nucleares' # Este url não existe
response_erro = requests.get(url_inexistente) # Pega o conteúdo de uma página inexistente
response_erro # Mostra a resposta

Explicação, o que o requests.get retorna. Exemplos 0, com websites aleatórios.

E para ver o conteúdo adquirido, é só invocar o atributo `.content` ou `.text`:

In [ ]:
print(response.content) # Imprime todo o conteúdo
print('------------------------------------------')
print(response.text[:1000]) # Imprime os 1000 primeiros caracteres do .text

b'<!DOCTYPE html>\n<html lang="pt-br" dir="ltr">\n  <head>\n    <!-- Google Tag Manager -->\n<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({\'gtm.start\':\nnew Date().getTime(),event:\'gtm.js\'});var f=d.getElementsByTagName(s)[0],\nj=d.createElement(s),dl=l!=\'dataLayer\'?\'&l=\'+l:\'\';j.async=true;j.src=\n\'https://www.googletagmanager.com/gtm.js?id=\'+i+dl;f.parentNode.insertBefore(j,f);\n})(window,document,\'script\',\'dataLayer\',\'GTM-5CMN2JM7\');</script>\n<!-- End Google Tag Manager -->\n    <meta charset="utf-8" />\n<link rel="canonical" href="https://www.eel.usp.br/ensino/graduacao/cursos" />\n<meta name="google-site-verification" content="PesJBsX8RIoy-nxDHZFBSeomhG9i6nBa3KOFCSDGGio" />\n<meta name="yandex-verification" content="5d4413d957a06bb0" />\n<meta name="Generator" content="Drupal 10 (https://www.drupal.org)" />\n<meta name="MobileOptimized" content="width" />\n<meta name="HandheldFriendly" content="true" />\n<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n<link rel="icon" href="/sites/files/eel/publico/favicon.ico" type="image/vnd.microsoft.icon" />\n<link rel="alternate" hreflang="und" href="https://www.eel.usp.br/ensino/graduacao/cursos" />\n<script>window.a2a_config=window.a2a_config||{};a2a_config.callbacks=[];a2a_config.overlays=[];a2a_config.templates={};</script>\n\n    <title>Cursos Oferecidos pela Escola | Escola de Engenharia de Lorena</title>\n    <link rel="stylesheet" media="all" href="/sites/files/eel/publico/css/css_kPBcOOoyrr_B8CJXWx-qZvTrUUWt1LIIkFNcKhgX7Wk.css?delta=0&amp;language=pt-br&amp;theme=gavias_emon&amp;include=eJx1jVkOwyAMRC9EQT1RZcBBVgyOMEmT23dJ2qbbjzWeefZAjE2gLA42YbsqpZnQY6Qm9QQhSI0kxT3VimCJJghL9TI7nCEPjEeTYCLQk2cJvR-JI1b3w7Ogik1fnzYG87UosXjgg7aFqaS3KN9wqz0VG7GDkdsjHiDhR-HO-tenTLuDdftiddGG2XlQNBPhWd192ixxZLwA7bt-qw" />\n<link rel="stylesheet" media="all" href="/sites/files/eel/publico/css/css_DbjwzAGSY3Lm57rvn7J57IDwCx-FuCXm9qSrssDB0ro.css?delta=1&amp;language=pt-br&amp;theme=gavias_emon&amp;include=eJx1jVkOwyAMRC9EQT1RZcBBVgyOMEmT23dJ2qbbjzWeefZAjE2gLA42YbsqpZnQY6Qm9QQhSI0kxT3VimCJJghL9TI7nCEPjEeTYCLQk2cJvR-JI1b3w7Ogik1fnzYG87UosXjgg7aFqaS3KN9wqz0VG7GDkdsjHiDhR-HO-tenTLuDdftiddGG2XlQNBPhWd192ixxZLwA7bt-qw" />\n<link rel="stylesheet" media="all" href="/sites/files/eel/publico/css/css_GR5Os8-XYAfcqWxDgVtlv7oREIdKg3j_AAiYjmi15B4.css?delta=2&amp;language=pt-br&amp;theme=gavias_emon&amp;include=eJx1jVkOwyAMRC9EQT1RZcBBVgyOMEmT23dJ2qbbjzWeefZAjE2gLA42YbsqpZnQY6Qm9QQhSI0kxT3VimCJJghL9TI7nCEPjEeTYCLQk2cJvR-JI1b3w7Ogik1fnzYG87UosXjgg7aFqaS3KN9wqz0VG7GDkdsjHiDhR-HO-tenTLuDdftiddGG2XlQNBPhWd192ixxZLwA7bt-qw" />\n<link rel="stylesheet" media="all" href="/sites/files/eel/publico/css/css_Hln4BE_lAYdkv7rVbsd9503UZ57bxJPJgnMh3q-iEGQ.css?delta=3&amp;language=pt-br&amp;theme=gavias_emon&amp;include=eJx1jVkOwyAMRC9EQT1RZcBBVgyOMEmT23dJ2qbbjzWeefZAjE2gLA42YbsqpZnQY6Qm9QQhSI0kxT3VimCJJghL9TI7nCEPjEeTYCLQk2cJvR-JI1b3w7Ogik1fnzYG87UosXjgg7aFqaS3KN9wqz0VG7GDkdsjHiDhR-HO-tenTLuDdftiddGG2XlQNBPhWd192ixxZLwA7bt-qw" />\n<link rel="stylesheet" media="all" href="/sites/files/eel/publico/css/css_JTYV1x4SS2PfclBsZODoAyrSJPJ__J-My8I7EgFnLqw.css?delta=4&amp;language=pt-br&amp;theme=gavias_emon&amp;include=eJx1jVkOwyAMRC9EQT1RZcBBVgyOMEmT23dJ2qbbjzWeefZAjE2gLA42YbsqpZnQY6Qm9QQhSI0kxT3VimCJJghL9TI7nCEPjEeTYCLQk2cJvR-JI1b3w7Ogik1fnzYG87UosXjgg7aFqaS3KN9wqz0VG7GDkdsjHiDhR-HO-tenTLuDdftiddGG2XlQNBPhWd192ixxZLwA7bt-qw" />\n<link rel="stylesheet" media="all" href="//fonts.googleapis.com/css?family=Roboto:400,500,700,900" />\n<link rel="stylesheet" media="all" href="//fonts.googleapis.com/css?family=Montserrat:400,700" />\n<link rel="stylesheet" media="all" href="/sites/files/eel/publico/css/css_YURJesXtq1ZXyRfkCbNQjUws8SP3nFlWJyDF-H8Qk1Q.css?delta=7&amp;language=pt-br&amp;theme=gavias_emon&amp;include=eJx1jVkOwyAMRC9EQT1RZcBBVgyOMEmT23dJ2qbbjzWeefZAjE2gLA42YbsqpZnQY6Qm9QQhSI0kxT3VimCJJghL9TI7nCEPjEeTYCLQk2cJvR-JI1b3w7Ogik1fnzYG87UosXjgg7aFqaS3KN9wqz0VG7GDkdsjHiDhR-HO-tenTLuDdftiddGG2XlQNBPhWd192ixxZLwA7bt-qw" />\n\n\n    <script type="application/json" data-drupal-selector="drupal-settings-json">{"path":{"baseUrl":"\\/","pathPrefix":"","currentPath":"node\\/99","currentPathIsAdmin":false,"isFront":false,"currentLanguage":"pt-br"},"pluralDelimiter":"\\u0003","suppressDeprecationErrors":true,"colorbox":{"opacity":"0.85","current":"{current} de {total}","previous":"\\u00ab Anterior","next":"Pr\\u00f3ximo \\u00bb","close":"Close","maxWidth":"98%","maxHeight":"98%","fixed":true,"mobiledetect":true,"mobiledevicewidth":"480px"},"ckeditorAccordion":{"accordionStyle":{"collapseAll":null,"keepRowsOpen":null,"animateAccordionOpenAndClose":1,"openTabsWithHash":1}},"user":{"uid":0,"permissionsHash":"79d873a042fb0f6dbb00f5bc9f7e9369069a4756b90b80ada4c308842cc35563"}}</script>\n<script src="/sites/files/eel/publico/js/js_KZCeZy_UjLlsjkhFPUdZwrepTyDhF0BI-IFBYQD0O48.js?scope=header&amp;delta=0&amp;language=pt-br&amp;theme=gavias_emon&amp;include=eJx1juEOwjAIhF-oro_U0IINGYIp1bi3d8nmXBr9d99xHABiN9Alwi6mazPtocyE3K0lKMUasmk81BYhxVBMrGV7RVbuByVWYaU4cKjwZPCUxcqcHyxILf7wJnCn7t8re4Zu6xNVLINcvC9rZf2M7lBpaDxZ_wpd-LSw0Zh9A2lhciY"></script>\n<script src="/sites/files/eel/publico/js/js_xz-eEuV_fVsnzMj7RGbSMO4IuHReXu3hUDfOnysZT3U.js?scope=header&amp;delta=1&amp;language=pt-br&amp;theme=gavias_emon&amp;include=eJx1juEOwjAIhF-oro_U0IINGYIp1bi3d8nmXBr9d99xHABiN9Alwi6mazPtocyE3K0lKMUasmk81BYhxVBMrGV7RVbuByVWYaU4cKjwZPCUxcqcHyxILf7wJnCn7t8re4Zu6xNVLINcvC9rZf2M7lBpaDxZ_wpd-LSw0Zh9A2lhciY"></script>\n<script src="/sites/files/eel/publico/js/js_m4PlagmLW23uV8AeVDEyfMEp5BTqgLyT0NBzQGeo3R8.js?scope=header&amp;delta=2&amp;language=pt-br&amp;theme=gavias_emon&amp;include=eJx1juEOwjAIhF-oro_U0IINGYIp1bi3d8nmXBr9d99xHABiN9Alwi6mazPtocyE3K0lKMUasmk81BYhxVBMrGV7RVbuByVWYaU4cKjwZPCUxcqcHyxILf7wJnCn7t8re4Zu6xNVLINcvC9rZf2M7lBpaDxZ_wpd-LSw0Zh9A2lhciY"></script>\n<script src="/sites/files/eel/publico/js/js_j-htrVBH8Q-4Z_3k_rDDt3m-FGj4HjZssoSpkiPCQEs.js?scope=header&amp;delta=3&amp;language=pt-br&amp;theme=gavias_emon&amp;include=eJx1juEOwjAIhF-oro_U0IINGYIp1bi3d8nmXBr9d99xHABiN9Alwi6mazPtocyE3K0lKMUasmk81BYhxVBMrGV7RVbuByVWYaU4cKjwZPCUxcqcHyxILf7wJnCn7t8re4Zu6xNVLINcvC9rZf2M7lBpaDxZ_wpd-LSw0Zh9A2lhciY"></script>\n\n\n    <link rel="stylesheet" href="/themes/gavias_emon/css/customize.css" media="screen" />\n    <link rel="stylesheet" href="/themes/gavias_emon/css/custom.css" media="screen" />\n    <link rel="stylesheet" href="/themes/gavias_emon/css/update.css" media="screen" />\n\n    \n    \n  </head>\n  <body class="exclude-node-title gavias-pagebuilder layout-no-sidebars not-preloader www-eel-usp-br ensino graduacao cursos page-node-99">\n  <!-- Google Tag Manager (noscript) -->\n<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5CMN2JM7"\nheight="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>\n<!-- End Google Tag Manager (noscript) -->\n\n    <a href="#main-content" class="visually-hidden focusable">\n      Pular para o conte\xc3\xbado principal\n    </a>\n    \n      <div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas>\n    <div class="body-page">\n\n   \n   <header id="header" class="header-v3">\n\n      <div class="topbar">\n      <div class="topbar-inner">\n        <div class="container">\n          <div class="content">  <div>\n    <div class="language-switcher-language-url block block-language block-language-blocklanguage-interface" id="block-seletordeidioma" role="navigation">\n  \n      <h2 class="block-title" ><span>Seletor de idioma</span></h2>\n    \n      <div class="content block-content">\n      <ul class="links"><li hreflang="pt-br" data-drupal-link-system-path="node/99" class="pt-br is-active" aria-current="page"><a href="/ensino/graduacao/cursos" class="language-link is-active" hreflang="pt-br" data-drupal-link-system-path="node/99" aria-current="page">Portugu\xc3\xaas, Brasil</a></li><li hreflang="en" data-drupal-link-system-path="node/99" class="en"><a href="/en/ensino/graduacao/cursos" class="language-link" hreflang="en" data-drupal-link-system-path="node/99">English</a></li></ul>\n    </div>\n  </div>\n\n  </div>\n</div>\n        </div>\n      </div>\n    </div>\n  \n          \n  <div class="gv-sticky-menu">\n     <div class="header-main">\n        <div class="container">\n           <div class="header-main-inner p-relative">\n              <div class="row">\n                <div class="col-md-3 col-xs-6 branding">\n                                        <div>\n    <div id="block-gavias-emon-sitebranding" class="margin-top-10 clearfix site-branding block block-system block-system-branding-block no-title">\n  \n    \n     \n    <a href="/" title="In\xc3\xadcio" rel="home" class="site-branding-logo padding-top-20">\n      <img src="/sites/files/eel/publico/logo_eel_2017.png" alt="In\xc3\xadcio" />\n    </a>  \n   \n   \n  </div>\n\n  </div>\n\n                                  </div>\n\n                <div class="col-md-9 col-xs-6 p-static">\n                  <div class="main-menu">\n                      <div class="navigation area-main-menu">\n                        <div class="area-inner">\n                                                        <div>\n    <nav aria-labelledby="block-menusuperior-menu" id="block-menusuperior" class="block block-menu navigation menu--menu-superior">\n          \n  \n  <h2  class="visually-hidden block-title block-title" id="block-menusuperior-menu"><span>Menu superior</span></h2>\n  \n  <div class="block-content">\n                 \n<div class="gva-navigation">\n\n              <ul class="gva_menu">\n        \n            <li  class="menu-item">\n        <a href="/home-eel-4" gva_layout="menu-list" gva_layout_columns="3" gva_block="gavias_emon_linkfooter" data-drupal-link-system-path="node/95">Home</a>\n        \n      </li>\n    \n            <li  class="menu-item menu-item--expanded">\n        <a href="/comunidade/alunos" gva_layout="menu-list" gva_layout_columns="3" gva_block="acessorapido" data-drupal-link-system-path="node/101">Comunidade</a>\n                                <ul class="menu sub-menu">\n        \n            <li  class="menu-item">\n        <a href="/comunidade/alunos" gva_layout="menu-list" gva_layout_columns="3" gva_block="acessorapido" data-drupal-link-system-path="node/101">Alunos</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="/comunidade/ex-alunos" gva_layout="menu-list" gva_layout_columns="3" gva_block="gavias_emon_advrightheader" data-drupal-link-system-path="node/2784">Ex-alunos</a>\n        \n      </li>\n        </ul>\n  \n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="https://www.bibliotecas.eel.usp.br" target="_blank" gva_layout="menu-list" gva_layout_columns="3" gva_block="acessorapido">Biblioteca</a>\n        \n      </li>\n    \n            <li  class="menu-item menu-item--expanded">\n        <a href="/informacoes" gva_layout="menu-list" gva_layout_columns="3" gva_block="gavias_emon_advrightheader" data-drupal-link-system-path="node/3085">Informa\xc3\xa7\xc3\xb5es</a>\n                                <ul class="menu sub-menu">\n        \n            <li  class="menu-item">\n        <a href="/form/fale-conosco-eel" gva_layout="menu-list" gva_layout_columns="3" gva_block="gavias_emon_advrightheader" data-drupal-link-system-path="webform/fale_conosco_eel">Fale Conosco</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="/informacoes/tel-emails" gva_layout="menu-list" gva_layout_columns="3" gva_block="gavias_emon_advrightheader" data-drupal-link-system-path="node/128">Emails e Telefones da EEL</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="/informacoes/locais" data-drupal-link-system-path="informacoes/locais">Locais</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="https://listas.eel.usp.br" gva_layout="menu-list" gva_layout_columns="3" gva_block="acessorapido">Listas de discuss\xc3\xa3o</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="/informacoes/rotas-de-acesso-ao-campus" gva_layout="menu-list" gva_layout_columns="3" gva_block="acessorapido" data-drupal-link-system-path="node/1709">Rotas de acesso ao Campus</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="https://sistemas.eel.usp.br/material-apoio/visualizar.php" gva_layout="menu-list" gva_layout_columns="3" gva_block="acessorapido">Material de Apoio para Aulas N\xc3\xa3o-Presenciais</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="https://meet.google.com/mbz-xpuw-ens" gva_layout="menu-list" gva_layout_columns="3" gva_block="acessorapido">Sala Virtual no Google Meet</a>\n        \n      </li>\n        </ul>\n  \n        \n      </li>\n    \n            <li  class="menu-item menu-item--expanded">\n        <a href="" gva_layout="menu-list" gva_layout_columns="3" gva_block="acessorapido">Servi\xc3\xa7os</a>\n                                <ul class="menu sub-menu">\n        \n            <li  class="menu-item">\n        <a href="https://www.puspl.usp.br/institucional/estrutura-organizacional/scinfo/sistemas-scinfo" target="_blank" gva_layout="menu-list" gva_layout_columns="3" gva_block="acessorapido">Sistemas EEL</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="http://sistemas.usp.br/" gva_layout="menu-list" gva_layout_columns="3" gva_block="gavias_emon_linkfooter">Sistemas USP</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="/institucional/servicos/telefonia" gva_layout="menu-list" gva_layout_columns="3" gva_block="gavias_emon_linkfooter">Telefonia</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="https://webmail.eel.usp.br" gva_layout="menu-list" gva_layout_columns="3" gva_block="gavias_emon_linkfooter">Webmail EEL</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="http://email.usp.br" gva_layout="menu-list" gva_layout_columns="3" gva_block="gavias_emon_linkfooter">Webmail USP</a>\n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="https://sistemas.eel.usp.br/caixa_sugestao" gva_layout="menu-list" gva_layout_columns="3" gva_block="acessorapido">Caixa de Sugest\xc3\xa3o</a>\n        \n      </li>\n        </ul>\n  \n        \n      </li>\n    \n            <li  class="menu-item">\n        <a href="https://www5.usp.br/transparencia/" target="_blank" gva_layout="menu-list" gva_layout_columns="3" gva_block="gavias_emon_advrightheader">Transpar\xc3\xaancia</a>\n        \n      </li>\n        </ul>\n  \n\n</div>\n\n        </div>\n</nav>\n\n  </div>\n\n                                                                                   <div class="gva-search-region search-region">\n                                <span class="icon"><i class="fa fa-search"></i></span>\n                                <div class="search-content">\n                                    <div>\n    <div id="block-formulariodebuscagoogle" class="block block-block-content block-block-contentcd73726c-f673-403f-9500-da20e8e6174d no-title">\n  \n    \n      <div class="content block-content">\n                  <div><form action="https://site.eel.usp.br/busca-google" id="formBusca" method="POST" name="formBusca">\n<div class="formBusca">\n<div class="inputText"><input autofocus class="form-text" name="s" placeholder="Digite o que deseja buscar" size="25" style type="text"></div>\n\n<div class="buttonEel" style="margin-top: 10px;"><input class="form-submit art-button" id="edit-submit" name="op" onclick="document.formBusca.action=\'https://site.eel.usp.br/busca-google/?q=\' + document.formBusca.s.value; document.formBusca.target=\'\'; document.formBusca.submit();" type="button" value="EEL (tudo)"></div>\n\n<div class="buttonUsp" style="margin-top: 10px;"><input class="form-submit art-button" id="edit-submit" name="btBuscaUsp" onclick="document.formBusca.action=\'https://www5.usp.br/?s=\' + document.formBusca.s.value + \'&amp;busca=g\'; document.formBusca.target=\'_blank\'; document.formBusca.submit();" type="button" value="USP (tudo)"></div>\n\n<div class="buttonPessoas" style="margin-top: 10px;"><input class="form-submit art-button" id="edit-submit" name="btBuscaPessoas" onclick="document.formBusca.action=\'https://sistemas.eel.usp.br/pesquisa/busca.php\';document.formBusca.s.name=\'txt_pesquisa\'; document.formBusca.target=\'_blank\'; document.formBusca.submit();document.formBusca.txt_pesquisa.name=\'s\';" type="button" value="Pessoas (eel)"></div>\n</div>\n</form>\n\n<p>&nbsp;</p>\n</div>\n      \n    </div>\n  </div>\n\n  </div>\n\n                                </div>\n                              </div>\n                                                   </div>\n                     </div>\n                  </div>\n                </div>\n              </div>\n           </div>\n        </div>\n     </div>\n\n     <div class="header-bottom">\n        <div class="main-menu">\n          <div class="container">\n             <div class="row">\n                <div class="col-xs-12 area-main-menu">\n                  <div class="p-static">\n                  <div class="menu--main">\n                      <div class="navigation menu--main">\n                        <div class="area-inner">\n                                                        <div>\n    <nav aria-labelledby="block-gavias-emon-mainnavigation-menu" id="block-gavias-emon-mainnavigation" class="block block-menu navigation menu--main">\n          \n  \n  <h2  class="visually-hidden block-title block-title" id="block-gavias-emon-mainnavigation-menu"><span>Main navigation</span></h2>\n  \n  <div class="block-content">\n                 \n<div class="gva-navigation">\n\n              <ul class="clearfix gva_menu gva_menu_main">\n                             \n         \n                  \n            <li  class="menu-item menu-item--expanded  gva-mega-menu megamenu menu-grid menu-columns-4">\n        <a href="/institucional/instituicao">\n                      <i class="fa fa-university"></i>\n                    A EEL\n                      <span class="icaret nav-plus fa fa-angle-down"></span>\n            \n        </a>\n          \n                                <ul class="menu sub-menu">\n                              \n            <li  class="menu-item menu-item--expanded ">\n        <a href="/institucional/instituicao">\n                    A EEL\n                      <span class="icaret nav-plus fa fa-angle-down"></span>\n            \n        </a>\n          \n                                <ul class="menu sub-menu">\n                              \n            <li  class="menu-item ">\n        <a href="/institucional/instituicao">\n                    Sobre a EEL\n            \n        </a>\n          \n              </li>\n                          \n            <li  class="menu-item ">\n        <a href="http://www.crint.eel.usp.br">\n                    Comiss\xc3\xa3o de Rel. Internacionais\n            \n        </a>\n          \n              </li>\n                          \n            <li  class="menu-item">\n        <a href="/institucional/organizacao-administrativa/comissoes-estatutarias/comissao-de-inclusao-e-pertencimento">\n                    Comiss\xc3\xa3o de Inclus\xc3\xa3o e Pertencimento\n            \n        </a>\n          \n              </li>\n                          \n            <li  class="menu-item ">\n        <a href="/calouros">\n                    Calouros\n            \n        </a>\n          \n              </li>\n                          \n            <li  class="menu-item ">\n        <a href="/informacoes/locais">\n                    Locais\n            \n        </a>\n          \n              </li>\n        </ul>\n  \n              </li>\n

`.content` traz o conteúdo bytes, sem ser decodificado:

In [ ]:
type(response.content) # Mostra o tipo de response.content

bytes

Já `.text` decoficida o texto, e retorna o `HTML` da página

In [ ]:
type(response.text) # Mostra o tipo de response.text

str

### `pprint`
Como vimos, ao utilizar print(response.text), o texto ficou desorganizado. A biblioteca `pprint` (*pretty-print*) permite mostrar esse texto com indentação e formatação adequada.  
Seu uso é da forma:  


```
texto_qualquer = '...'
pprint.pprint(texto_qualquer)
```

In [ ]:
import pprint # Importar a biblioteca

In [ ]:
pprint.pprint(response.text[:1000]) # Mostra os primeiros 1000 caracteres da resposta

('<!DOCTYPE html>\n'
 '<html lang="pt-br" dir="ltr">\n'
 '  <head>\n'
 '    <!-- Google Tag Manager -->\n'
 "<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':\n"
 "new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],\n"
 "j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=\n"
 "'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);\n"
 "})(window,document,'script','dataLayer','GTM-5CMN2JM7');</script>\n"
 '<!-- End Google Tag Manager -->\n'
 '    <meta charset="utf-8" />\n'
 '<link rel="canonical" href="https://www.eel.usp.br/ensino/graduacao/cursos" '
 '/>\n'
 '<meta name="google-site-verification" '
 'content="PesJBsX8RIoy-nxDHZFBSeomhG9i6nBa3KOFCSDGGio" />\n'
 '<meta name="yandex-verification" content="5d4413d957a06bb0" />\n'
 '<meta name="Generator" content="Drupal 10 (https://www.drupal.org)" />\n'
 '<meta name="MobileOptimized" content="width" />\n'
 '<meta name="HandheldFriendly" content="true" />\n'
 '<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
 '<link rel="icon')

In [ ]:
print(type(response.content))
print(type(response.text))

<class 'bytes'>
<class 'str'>

## JSON

Já trabalhamos com arquivos `.json`, porém utilizamos um link direto:

In [ ]:
url_json = 'https://raw.githubusercontent.com/JCFDGG/LOB1266-PUB/refs/heads/main/ExemplosAula/1/brasiliaexemplo.json'
pd.read_json(url_json) # Lê o arquivo .json como DataFrame

,PRE_INS,TEM_SEN,VL_LATITUDE,PRE_MAX,RAD_GLO,PTO_INS,TEM_MIN,VL_LONGITUDE,UMD_MIN,PTO_MAX,...,VEN_VEL,PTO_MIN,TEM_MAX,TEN_BAT,VEN_RAJ,TEM_CPU,TEM_INS,UMD_INS,HR_MEDICAO,CIDADE
2024-01-01,885.420833,22.504167,-15.789444,885.737500,637.083333,18.666667,21.383333,-47.925833,78.125000,19.220833,...,1.658333,18.166667,22.745833,13.050000,4.150000,23.708333,21.995833,82.541667,1150,Brasilia
2024-01-02,884.200000,21.845833,-15.789444,884.441667,683.066667,19.570833,20.670833,-47.925833,88.000000,19.962500,...,1.787500,19.150000,21.679167,13.029167,4.425000,22.791667,21.187500,91.000000,1150,Brasilia
2024-01-03,884.170833,20.491667,-15.789444,884.420833,421.879167,19.370833,20.216667,-47.925833,91.875000,19.654167,...,2.250000,19.116667,20.845833,12.987500,5.045833,21.916667,20.537500,93.375000,1150,Brasilia
2024-01-04,884.825000,19.820833,-15.789444,885.058333,368.541667,19.491667,20.095833,-47.925833,93.166667,19.770833,...,2.529167,19.325000,20.712500,12.995833,5.720833,21.750000,20.375000,94.750000,1150,Brasilia
2024-01-05,885.095833,19.750000,-15.789444,885.354167,485.345833,19.004167,20.004167,-47.925833,90.125000,19.300000,...,2.545833,18.737500,20.816667,13.033333,6.041667,21.791667,20.400000,92.125000,1150,Brasilia

---

Mas alguns websites também retornam dados em formatos `json`, porém não diretamente em arquivos. Para isto, vamos explorar algumas APIs:

## APIs

Uma API (Interface de Programação de Aplicações) é um conjunto simplificado de regras com interfaces que permitem comunicar com o sistema, e para nós, sua capacidade mais importante é a de coleta de dados.  
APIs são especialmente úteis para *data mining*, que é o processo de aquisição e exploração de dados. Elas permitem acesso de grandes volumes, de forma automática.

### Exemplo 1

Segue um exemplo básico de API, porém útil:  
A API do INMET - comunicada através do url (`https://apitempo.inmet.gov.br/token/estacao/`) - retorna json já apropriadamente formatado.

#### Explicação da API do INMET
##### Como adquirir um token

##### Como utilizar:
Você provavelmente recebeu uma mensagem deste tipo em seu e-mail, caso já adquiriu token:
- Os códigos das estações estão nos links:  
[Manuais](https://apitempo.inmet.gov.br/estacoes/M)  
[Automáticas](https://apitempo.inmet.gov.br/estacoes/T)


- Para recuperar dados horários referentes a estações automáticas ou manuais, segue o modelo:
`apitempo.inmet.gov.br/token/estacao/:data_inicial/:data_final/:cod_estacao/:seu_token`  
Por exemplo, para pegar dados de 2022-11-01 a 2022-12-03 da estação A001:
`https://apitempo.inmet.gov.br/token/estacao/2022-11-01/2022-11-01/A001/fbb192ba9f1a4673f6a62400943f391292d1d582fffbc5fd21ab5239a681929a`


- Para recuperar dados horários de TODAS as estações automáticas de um determinado dia e horário::
`apitempo.inmet.gov.br/token/estacao/dados/:data/:hora/:seu_token`
Por exemplo, pegar dados de 2022-11-01 às 00h00m: `https://apitempo.inmet.gov.br/token/estacao/dados/2022-11-01/0000/fbb192ba9f1a4673f6a62400943f391292d1d582fffbc5fd21ab5239a681929a`

- Para recuperar dados diários referentes a estação automática ou manual:
`apitempo.inmet.gov.br/token/estacao/diaria/:data_inicial/:data_final/:cod_estacao/:seu_token`
Por exemplo, pedir dados diários de 2022-11-01 às 2023-01-01 da estação A001: `https://apitempo.inmet.gov.br/token/estacao/diaria/2022-11-01/2023-01-01/A001/fbb192ba9f1a4673f6a62400943f391292d1d582fffbc5fd21ab5239a681929a`

Vamos tentar pegar os dados de 2022-11-01 da estação A001. Para isso, é conveniente colocar as diferentes partes do URL como diferentes variáveis:

Caso você já não tenha um token, use o seguinte:


```
ellPTm00R2FKaGNPclBrckd0SlFKR0dMUTZPcU12REs=zYONm4GaJhcOrPkrGtJQJGGLQ6OqMvDK
```

In [ ]:
url_base = ' https://apitempo.inmet.gov.br/token/estacao'
data_inicial = '2022-11-01'
data_final = '2022-11-30'
estacao = 'A001'
api_key = 'ellPTm00R2FKaGNPclBrckd0SlFKR0dMUTZPcU12REs=zYONm4GaJhcOrPkrGtJQJGGLQ6OqMvDK'

# Junta as diferentes partes do url em uma única string:
url_final = url_base + '/' + data_inicial + '/' + data_final + '/' + estacao + '/' + api_key
print(url_final) # Imprime o URL final

resposta = requests.get(url_final) # Coleta os dados de url_final

resposta_dic = resposta.json() # Transforma o url em formato json, semelhante a um dict

print(resposta_dic) # Imprime o dict

 https://apitempo.inmet.gov.br/token/estacao/2022-11-01/2022-11-30/A001/ellPTm00R2FKaGNPclBrckd0SlFKR0dMUTZPcU12REs=zYONm4GaJhcOrPkrGtJQJGGLQ6OqMvDK

Como a API já retorna um arquivo json, pode-se usar o `url_final` diretamente:

In [ ]:
df = pd.read_json(url_final)
df

,DC_NOME,PRE_INS,TEM_SEN,VL_LATITUDE,PRE_MAX,UF,RAD_GLO,PTO_INS,TEM_MIN,VL_LONGITUDE,...,VEN_VEL,PTO_MIN,TEM_MAX,TEN_BAT,VEN_RAJ,TEM_CPU,TEM_INS,UMD_INS,CD_ESTACAO,HR_MEDICAO
0,BRASILIA,886.9,15.4,-15.789444,887.0,DF,-2.8,17.4,18.7,-47.925833,...,3.7,17.2,19.5,12.7,7.0,21,18.7,92,A001,0
1,BRASILIA,887.0,16.9,-15.789444,887.0,DF,-2.9,17.5,18.7,-47.925833,...,3.0,17.3,19.0,12.7,7.0,21,18.9,91,A001,100
2,BRASILIA,887.0,18.6,-15.789444,887.2,DF,-3.2,17.4,18.8,-47.925833,...,2.0,17.4,18.9,12.7,5.8,20,18.8,91,A001,200
3,BRASILIA,886.4,19.9,-15.789444,887.0,DF,-3.2,17.1,18.7,-47.925833,...,1.1,17.1,18.9,12.7,4.7,20,18.7,91,A001,300
4,BRASILIA,885.9,20.4,-15.789444,886.5,DF,-3.5,17.5,18.5,-47.925833,...,0.8,17.1,18.8,12.7,1.8,20,18.7,93,A001,400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,BRASILIA,878.6,21.8,-15.789444,879.3,DF,2401.7,12.5,23.7,-47.925833,...,2.9,11.8,24.9,14.3,7.5,26,24.6,47,A001,1900
716,BRASILIA,878.8,22.8,-15.789444,878.9,DF,1498.2,13.2,24.1,-47.925833,...,2.2,11.6,25.2,13.6,6.7,27,24.6,49,A001,2000
717,BRASILIA,879.2,20.3,-15.789444,879.3,DF,445.5,15.2,21.6,-47.925833,...,2.2,12.8,24.8,13.1,6.2,26,21.6,67,A001,2100
718,BRASILIA,879.9,19.6,-15.789444,879.9,DF,24.1,15.3,19.8,-47.925833,...,1.6,15.1,21.6,12.7,4.1,24,19.8,75,A001,2200
719,BRASILIA,880.5,18.6,-15.789444,880.5,DF,-3.5,15.4,19.0,-47.925833,...,1.8,15.3,19.9,12.7,3.1,22,19.0,80,A001,2300

Caso queremos usar resposta_dic para fazer a `DataFrame`, usamos o método: `pd.DataFrame.from_dict(dict_qualquer)`:

In [ ]:
df = pd.DataFrame.from_dict(resposta_dic)
df

,DC_NOME,PRE_INS,TEM_SEN,VL_LATITUDE,PRE_MAX,UF,RAD_GLO,PTO_INS,TEM_MIN,VL_LONGITUDE,...,VEN_VEL,PTO_MIN,TEM_MAX,TEN_BAT,VEN_RAJ,TEM_CPU,TEM_INS,UMD_INS,CD_ESTACAO,HR_MEDICAO
0,BRASILIA,886.9,15.4,-15.78944444,887,DF,-2.8,17.4,18.7,-47.92583332,...,3.7,17.2,19.5,12.7,7,21,18.7,92,A001,0000
1,BRASILIA,887,16.9,-15.78944444,887,DF,-2.9,17.5,18.7,-47.92583332,...,3,17.3,19,12.7,7,21,18.9,91,A001,0100
2,BRASILIA,887,18.6,-15.78944444,887.2,DF,-3.2,17.4,18.8,-47.92583332,...,2,17.4,18.9,12.7,5.8,20,18.8,91,A001,0200
3,BRASILIA,886.4,19.9,-15.78944444,887,DF,-3.2,17.1,18.7,-47.92583332,...,1.1,17.1,18.9,12.7,4.7,20,18.7,91,A001,0300
4,BRASILIA,885.9,20.4,-15.78944444,886.5,DF,-3.5,17.5,18.5,-47.92583332,...,0.8,17.1,18.8,12.7,1.8,20,18.7,93,A001,0400
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,BRASILIA,878.6,21.8,-15.78944444,879.3,DF,2401.7,12.5,23.7,-47.92583332,...,2.9,11.8,24.9,14.3,7.5,26,24.6,47,A001,1900
716,BRASILIA,878.8,22.8,-15.78944444,878.9,DF,1498.2,13.2,24.1,-47.92583332,...,2.2,11.6,25.2,13.6,6.7,27,24.6,49,A001,2000
717,BRASILIA,879.2,20.3,-15.78944444,879.3,DF,445.5,15.2,21.6,-47.92583332,...,2.2,12.8,24.8,13.1,6.2,26,21.6,67,A001,2100
718,BRASILIA,879.9,19.6,-15.78944444,879.9,DF,24.1,15.3,19.8,-47.92583332,...,1.6,15.1,21.6,12.7,4.1,24,19.8,75,A001,2200
719,BRASILIA,880.5,18.6,-15.78944444,880.5,DF,-3.5,15.4,19,-47.92583332,...,1.8,15.3,19.9,12.7,3.1,22,19,80,A001,2300

### Exemplo 2

Vamos usar uma API um pouco mais complicada, que gera dados aleatórios em um formato que exige ser trabalhado:  
`url = https://randomuser.me/api`

In [ ]:
url = 'https://randomuser.me/api' # Salva o URL
resposta = requests.get(url) # Coleta o conteúdo do url
pprint.pprint(resposta.text) # Usa pprint para mostrar o texto da resposta

('{"results":[{"gender":"male","name":{"title":"Monsieur","first":"Joel","last":"Bertrand"},"location":{"street":{"number":7147,"name":"Rue '
 'de '
 'L\'Abbaye"},"city":"Gansingen","state":"Zürich","country":"Switzerland","postcode":2796,"coordinates":{"latitude":"-57.5739","longitude":"-24.9017"},"timezone":{"offset":"-3:30","description":"Newfoundland"}},"email":"joel.bertrand@example.com","login":{"uuid":"714b85fd-faa4-4cd1-820f-2f7a3f8ac890","username":"angryzebra268","password":"biology","salt":"9OMsY2fs","md5":"dbee7e23021a9edaa980a6d42724e0dc","sha1":"442e1f8c43e3dbd05aaf6457599811359780fcb5","sha256":"8eb537fe19d0d7061ad9f11aa04c421339218419d0fa5f8990ecb1618609c91b"},"dob":{"date":"1998-01-09T22:51:19.338Z","age":27},"registered":{"date":"2011-06-14T19:19:53.951Z","age":13},"phone":"079 '
 '568 55 05","cell":"075 776 74 '
 '13","id":{"name":"AVS","value":"756.3751.2610.13"},"picture":{"large":"https://randomuser.me/api/portraits/men/68.jpg","medium":"https://randomuser.me/api/portraits/med/men/68.jpg","thumbnail":"https://randomuser.me/api/portraits/thumb/men/68.jpg"},"nat":"CH"}],"info":{"seed":"777c8950229c40e5","results":1,"page":1,"version":"1.4"}}')

Como vemos, a resposta veio no formato de json, e podemos converter em um `dict`:

In [ ]:
resposta_dic = resposta.json() # Transforma a resposta em dict
print(type(resposta_dic)) # Mostra o type da variável resposta_dic
print(resposta_dic) # Mostra a resposta_dic

<class 'dict'>
{'results': [{'gender': 'male', 'name': {'title': 'Monsieur', 'first': 'Joel', 'last': 'Bertrand'}, 'location': {'street': {'number': 7147, 'name': "Rue de L'Abbaye"}, 'city': 'Gansingen', 'state': 'Zürich', 'country': 'Switzerland', 'postcode': 2796, 'coordinates': {'latitude': '-57.5739', 'longitude': '-24.9017'}, 'timezone': {'offset': '-3:30', 'description': 'Newfoundland'}}, 'email': 'joel.bertrand@example.com', 'login': {'uuid': '714b85fd-faa4-4cd1-820f-2f7a3f8ac890', 'username': 'angryzebra268', 'password': 'biology', 'salt': '9OMsY2fs', 'md5': 'dbee7e23021a9edaa980a6d42724e0dc', 'sha1': '442e1f8c43e3dbd05aaf6457599811359780fcb5', 'sha256': '8eb537fe19d0d7061ad9f11aa04c421339218419d0fa5f8990ecb1618609c91b'}, 'dob': {'date': '1998-01-09T22:51:19.338Z', 'age': 27}, 'registered': {'date': '2011-06-14T19:19:53.951Z', 'age': 13}, 'phone': '079 568 55 05', 'cell': '075 776 74 13', 'id': {'name': 'AVS', 'value': '756.3751.2610.13'}, 'picture': {'large': 'https://randomuser.me/api/portraits/men/68.jpg', 'medium': 'https://randomuser.me/api/portraits/med/men/68.jpg', 'thumbnail': 'https://randomuser.me/api/portraits/thumb/men/68.jpg'}, 'nat': 'CH'}], 'info': {'seed': '777c8950229c40e5', 'results': 1, 'page': 1, 'version': '1.4'}}

Ao analisar um pouco o dicionário, percebe-se que os dados que queremos estão sob a chave `results`:

In [ ]:
resposta_dic['results'] # Pega o valor da chave "results"

[{'gender': 'male',
  'name': {'title': 'Monsieur', 'first': 'Joel', 'last': 'Bertrand'},
  'location': {'street': {'number': 7147, 'name': "Rue de L'Abbaye"},
   'city': 'Gansingen',
   'state': 'Zürich',
   'country': 'Switzerland',
   'postcode': 2796,
   'coordinates': {'latitude': '-57.5739', 'longitude': '-24.9017'},
   'timezone': {'offset': '-3:30', 'description': 'Newfoundland'}},
  'email': 'joel.bertrand@example.com',
  'login': {'uuid': '714b85fd-faa4-4cd1-820f-2f7a3f8ac890',
   'username': 'angryzebra268',
   'password': 'biology',
   'salt': '9OMsY2fs',
   'md5': 'dbee7e23021a9edaa980a6d42724e0dc',
   'sha1': '442e1f8c43e3dbd05aaf6457599811359780fcb5',
   'sha256': '8eb537fe19d0d7061ad9f11aa04c421339218419d0fa5f8990ecb1618609c91b'},
  'dob': {'date': '1998-01-09T22:51:19.338Z', 'age': 27},
  'registered': {'date': '2011-06-14T19:19:53.951Z', 'age': 13},
  'phone': '079 568 55 05',
  'cell': '075 776 74 13',
  'id': {'name': 'AVS', 'value': '756.3751.2610.13'},
  'picture': {'large': 'https://randomuser.me/api/portraits/men/68.jpg',
   'medium': 'https://randomuser.me/api/portraits/med/men/68.jpg',
   'thumbnail': 'https://randomuser.me/api/portraits/thumb/men/68.jpg'},
  'nat': 'CH'}]

Porém, percebe-se que os dados ainda estão em uma lista, então, para ter o dicionário final:

In [ ]:
dic_final = resposta_dic['results'][0] # Pega o primeiro item do valor da chave "results"
dic_final # Mostra dic_final

{'gender': 'male',
 'name': {'title': 'Monsieur', 'first': 'Joel', 'last': 'Bertrand'},
 'location': {'street': {'number': 7147, 'name': "Rue de L'Abbaye"},
  'city': 'Gansingen',
  'state': 'Zürich',
  'country': 'Switzerland',
  'postcode': 2796,
  'coordinates': {'latitude': '-57.5739', 'longitude': '-24.9017'},
  'timezone': {'offset': '-3:30', 'description': 'Newfoundland'}},
 'email': 'joel.bertrand@example.com',
 'login': {'uuid': '714b85fd-faa4-4cd1-820f-2f7a3f8ac890',
  'username': 'angryzebra268',
  'password': 'biology',
  'salt': '9OMsY2fs',
  'md5': 'dbee7e23021a9edaa980a6d42724e0dc',
  'sha1': '442e1f8c43e3dbd05aaf6457599811359780fcb5',
  'sha256': '8eb537fe19d0d7061ad9f11aa04c421339218419d0fa5f8990ecb1618609c91b'},
 'dob': {'date': '1998-01-09T22:51:19.338Z', 'age': 27},
 'registered': {'date': '2011-06-14T19:19:53.951Z', 'age': 13},
 'phone': '079 568 55 05',
 'cell': '075 776 74 13',
 'id': {'name': 'AVS', 'value': '756.3751.2610.13'},
 'picture': {'large': 'https://randomuser.me/api/portraits/men/68.jpg',
  'medium': 'https://randomuser.me/api/portraits/med/men/68.jpg',
  'thumbnail': 'https://randomuser.me/api/portraits/thumb/men/68.jpg'},
 'nat': 'CH'}

E como ainda há dicionários dentro de dicionários, podemos usar a função `pd.json_normalize(variavel_json)`:

In [ ]:
var_json = resposta_dic['results'][0] # Retoma o dicionário (json)
dic_norm = pd.json_normalize(var_json) # Normaliza o dicionário
pd.DataFrame(dic_norm) # Transforma o dicionário normalizado em DataFrame

,gender,email,phone,cell,nat,name.title,name.first,name.last,location.street.number,location.street.name,...,login.sha256,dob.date,dob.age,registered.date,registered.age,id.name,id.value,picture.large,picture.medium,picture.thumbnail
0,male,joel.bertrand@example.com,079 568 55 05,075 776 74 13,CH,Monsieur,Joel,Bertrand,7147,Rue de L'Abbaye,...,8eb537fe19d0d7061ad9f11aa04c421339218419d0fa5f...,1998-01-09T22:51:19.338Z,27,2011-06-14T19:19:53.951Z,13,AVS,756.3751.2610.13,https://randomuser.me/api/portraits/men/68.jpg,https://randomuser.me/api/portraits/med/men/68...,https://randomuser.me/api/portraits/thumb/men/...

Também é interessante fazer todas estas etapas em apenas uma linha:

In [ ]:
pd.DataFrame(pd.json_normalize(resposta.json()['results'][0]))

,gender,email,phone,cell,nat,name.title,name.first,name.last,location.street.number,location.street.name,...,login.sha256,dob.date,dob.age,registered.date,registered.age,id.name,id.value,picture.large,picture.medium,picture.thumbnail
0,male,joel.bertrand@example.com,079 568 55 05,075 776 74 13,CH,Monsieur,Joel,Bertrand,7147,Rue de L'Abbaye,...,8eb537fe19d0d7061ad9f11aa04c421339218419d0fa5f...,1998-01-09T22:51:19.338Z,27,2011-06-14T19:19:53.951Z,13,AVS,756.3751.2610.13,https://randomuser.me/api/portraits/men/68.jpg,https://randomuser.me/api/portraits/med/men/68...,https://randomuser.me/api/portraits/thumb/men/...

# Web scraping

*Web scraping* é a extração automatizada de dados de sites. Para nós, seu maior interesse é na extração de dados tabelados, ou até não-tabelados, que não estão disponíveis em arquivos separados.   
Vamos usar de exemplo uma tabela de um html adquirida do sistema [TABNET](https://datasus.saude.gov.br/informacoes-de-saude-tabnet/) do Datasus.

In [ ]:
url_tabnet = "https://github.com/JCFDGG/LOB1266-PUB/raw/refs/heads/main/ExemplosAula/webscrap/tabnet.html"

texto_tabnet = requests.get(url_tabnet).text # Pega o texto da resposta diretamente

pprint.pprint(texto_tabnet[:1000]) # Usa pprint para mostrar os dados

('<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" '
 '"http://www.w3.org/TR/html4/loose.dtd">\r\n'
 '<html lang="pt-BR"><HEAD>\r\n'
 '<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\r\n'
 '<TITLE>TabNet Win32 3.3:  Abastecimento de &aacute;gua - S&atilde;o '
 'Paulo</TITLE>\r\n'
 '<LINK REL="stylesheet" HREF="/tabnet/tabnet2.css" TYPE="text/css"><!-- com a '
 'opção JCSS -->\r\n'
 '<LINK REL="stylesheet" HREF="/tabnet/tabnetp2.css" MEDIA="print"  '
 'TYPE="text/css"><!-- com a opção JCSSP -->\r\n'
 '</HEAD>\r\n'
 '<BODY>\r\n'
 ' <div name="governo" class="todalargura">\r\n'
 ' <div class="testeira" cellspacing="0" cellpadding="0">\r\n'
 '   <div class="Escondido" style="background-color: #ffcc00;">\r\n'
 '      <div>\r\n'
 '         <a href="http://www.saude.gov.br" target="_blank">\r\n'
 '            <img alt="Ministério da Saúde" '
 'src="http://www.datasus.gov.br/gifs/principal_r1_c1_res.gif" height="21" '
 'id="img1" />\r\n'
 '         </a>\r\n'
 '     </div>\r\n'
 ' </div>\r\n'
 ' <div class="testeira" cellspacing="0" cellpadding="0">\r\n'
 '    <div class="info_saude">\r\n'
 ' ')

Vemos que não temos apenas a tabela, mas muitas informações desnecessárias para a análise. É possível isolar a tabela por métodos da classe `string`, mas é mais útil utilizar de `BeautifulSoup`:

## A biblioteca BeautifulSoup

A biblioteca `bs4` nos dá o método e classe `BeautifulSoup`. Então, importa-se assim:

In [ ]:
from bs4 import BeautifulSoup

Vamos salvar o processamento uma variável de nome `soup`, que precisa da lógica:


```
soup = BeautifulSoup( texto_html_qualquer, 'html5lib')
```

'html5lib' é um parser, que vai lidar com o html em si, e permitir extrair informações dele. Há outros, como o [nativo](https://docs.python.org/3/library/html.parser.html) ou o [lxml](https://lxml.de/), mas o [html5lib](https://github.com/html5lib/) permite maior flexibilidade e melhor compatibilidade com html "quebrado".  
Segue um exemplo, utilizando o TABNET:

In [ ]:
soup = BeautifulSoup(texto_tabnet,'html5lib')

De uma forma similar ao `pprint`, O método `soup.prettify()` mostra o html já formatado adequadamente:

In [ ]:
print(soup.prettify())

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="pt-BR">
 <head>
  <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
  <title>
   TabNet Win32 3.3:  Abastecimento de água - São Paulo
  </title>
  <link href="/tabnet/tabnet2.css" rel="stylesheet" type="text/css"/>
  <!-- com a opção JCSS -->
  <link href="/tabnet/tabnetp2.css" media="print" rel="stylesheet" type="text/css"/>
  <!-- com a opção JCSSP -->
 </head>
 <body>
  <div class="todalargura" name="governo">
   <div cellpadding="0" cellspacing="0" class="testeira">
    <div class="Escondido" style="background-color: #ffcc00;">
     <div>
      <a href="http://www.saude.gov.br" target="_blank">
       <img alt="Ministério da Saúde" height="21" id="img1" src="http://www.datasus.gov.br/gifs/principal_r1_c1_res.gif"/>
      </a>
     </div>
    </div>
    <div cellpadding="0" cellspacing="0" class="testeira">
     <div class="info_saude">
      <a alt="Informações de Saúde" href="/tabnet/tabnet.htm" title="Informações de Saúde">
       Informações de Saúde
      </a>
     </div>
     <div class="marca_tabnet">
      <p>
       DATASUS
       <span>
        Tecnologia da Informação a Serviço do SUS
        <a alt="MS/SE/Datasus" href="http://www.datasus.gov.br" title="MS/SE/Datasus">
        </a>
       </span>
      </p>
     </div>
     <div class="ajuda">
      <a href="/tabnet/tabdescr.htm">
       Ajuda
      </a>
     </div>
     <div class="notific">
      <a href="ibge/Abastecimento_de_Agua.pdf">
       Notas Técnicas
      </a>
      <p>
      </p>
     </div>
     <div class="datasus">
      <p>
       DATASUS
      </p>
     </div>
    </div>
    <table align="CENTER" class="tabdados">
     <colgroup>
      <col align="LEFT" valign="TOP"/>
     </colgroup>
     <colgroup>
      <col align="RIGHT" span="3" valign="TOP"/>
     </colgroup>
     <thead>
      <tr class="cabtabela">
       <td colspan="4">
        <h1 class="Nivel0">
         Abastecimento de água - São Paulo
        </h1>
        <b>
         Moradores por Ano segundo Município
        </b>
        <br/>
        <b>
         Período:
        </b>
        1991, 2000, 2010
       </td>
      </tr>
      <tr valign="BOTTOM">
       <th class="cabesquerdo">
        Município
       </th>
       <th class="cabmeio">
        1991
       </th>
       <th class="cabmeio">
        2000
       </th>
       <th class="cabdireito">
        2010
       </th>
      </tr>
     </thead>
     <tfoot>
      <tr valign="BOTTOM">
       <td class="rodape" colspan="4">
        <div class="rodape_htm">
         Fonte: IBGE - Censos Demográficos de 1991, 2000 e 2010
         <br/>
         Consulte o site da
         <a href="http://www.saude.sp.gov.br" target="_blank">
          Secretaria Estadual de Saúde
         </a>
         para mais informações.
        </div>
       </td>
      </tr>
     </tfoot>
     <tbody valign="BOTTOM">
      <tr align="right" class="separador">
       <td align="left">
        TOTAL
       </td>
       <td>
        31.284.067
       </td>
       <td>
        36.713.804
       </td>
       <td>
        40.943.200
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350010 ADAMANTINA
       </td>
       <td>
        31.893
       </td>
       <td>
        33.150
       </td>
       <td>
        33.471
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350020 ADOLFO
       </td>
       <td>
        3.271
       </td>
       <td>
        3.677
       </td>
       <td>
        3.556
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350030 AGUAI
       </td>
       <td>
        23.260
       </td>
       <td>
        27.983
       </td>
       <td>
        32.016
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350040 AGUAS DA PRATA
       </td>
       <td>
        6.616
       </td>
       <td>
        7.047
       </td>
       <td>
        7.503
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350050 AGUAS DE LINDOIA
       </td>
       <td>
        11.689
       </td>
       <td>
        15.960
       </td>
       <td>
        17.116
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350055 AGUAS DE SANTA BARBARA
       </td>
       <td>
        5.831
       </td>
       <td>
        5.059
       </td>
       <td>
        5.577
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350060 AGUAS DE SAO PEDRO
       </td>
       <td>
        1.614
       </td>
       <td>
        1.848
       </td>
       <td>
        2.680
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350070 AGUDOS
       </td>
       <td>
        31.484
       </td>
       <td>
        31.996
       </td>
       <td>
        34.237
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350075 ALAMBARI
       </td>
       <td>
        -
       </td>
       <td>
        3.627
       </td>
       <td>
        4.862
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350080 ALFREDO MARCONDES
       </td>
       <td>
        3.482
       </td>
       <td>
        3.692
       </td>
       <td>
        3.877
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350090 ALTAIR
       </td>
       <td>
        3.230
       </td>
       <td>
        3.471
       </td>
       <td>
        3.788
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350100 ALTINOPOLIS
       </td>
       <td>
        13.534
       </td>
       <td>
        15.321
       </td>
       <td>
        15.519
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350110 ALTO ALEGRE
       </td>
       <td>
        4.761
       </td>
       <td>
        4.212
       </td>
       <td>
        4.101
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350115 ALUMINIO
       </td>
       <td>
        -
       </td>
       <td>
        15.193
       </td>
       <td>
        16.766
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350120 ALVARES FLORENCE
       </td>
       <td>
        5.049
       </td>
       <td>
        4.297
       </td>
       <td>
        3.896
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350130 ALVARES MACHADO
       </td>
       <td>
        18.797
       </td>
       <td>
        22.602
       </td>
       <td>
        23.464
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350140 ALVARO DE CARVALHO
       </td>
       <td>
        3.096
       </td>
       <td>
        3.290
       </td>
       <td>
        3.287
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350150 ALVINLANDIA
       </td>
       <td>
        2.532
       </td>
       <td>
        2.830
       </td>
       <td>
        2.995
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350160 AMERICANA
       </td>
       <td>
        152.786
       </td>
       <td>
        181.503
       </td>
       <td>
        209.754
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350170 AMERICO BRASILIENSE
       </td>
       <td>
        20.039
       </td>
       <td>
        28.145
       </td>
       <td>
        34.339
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350180 AMERICO DE CAMPOS
       </td>
       <td>
        5.590
       </td>
       <td>
        5.578
       </td>
       <td>
        5.697
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350190 AMPARO
       </td>
       <td>
        50.194
       </td>
       <td>
        60.013
       </td>
       <td>
        65.510
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350200 ANALANDIA
       </td>
       <td>
        3.012
       </td>
       <td>
        3.552
       </td>
       <td>
        4.257
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350210 ANDRADINA
       </td>
       <td>
        51.756
       </td>
       <td>
        54.150
       </td>
       <td>
        54.208
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350220 ANGATUBA
       </td>
       <td>
        20.935
       </td>
       <td>
        19.227
       </td>
       <td>
        22.134
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350230 ANHEMBI
       </td>
       <td>
        3.443
       </td>
       <td>
        4.483
       </td>
       <td>
        5.561
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350240 ANHUMAS
       </td>
       <td>
        3.224
       </td>
       <td>
        3.374
       </td>
       <td>
        3.715
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350250 APARECIDA
       </td>
       <td>
        32.538
       </td>
       <td>
        34.301
       </td>
       <td>
        34.628
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350260 APARECIDA D'OESTE
       </td>
       <td>
        5.087
       </td>
       <td>
        4.918
       </td>
       <td>
        4.419
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350270 APIAI
       </td>
       <td>
        34.836
       </td>
       <td>
        27.001
       </td>
       <td>
        25.039
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350275 ARACARIGUAMA
       </td>
       <td>
        -
       </td>
       <td>
        11.018
       </td>
       <td>
        16.913
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350280 ARACATUBA
       </td>
       <td>
        158.842
       </td>
       <td>
        168.641
       </td>
       <td>
        180.517
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350290 ARACOIABA DA SERRA
       </td>
       <td>
        14.388
       </td>
       <td>
        19.661
       </td>
       <td>
        27.162
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350300 ARAMINA
       </td>
       <td>
        4.060
       </td>
       <td>
        4.721
       </td>
       <td>
        5.146
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350310 ARANDU
       </td>
       <td>
        5.613
       </td>
       <td>
        6.035
       </td>
       <td>
        6.078
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350315 ARAPEI
       </td>
       <td>
        -
       </td>
       <td>
        2.618
       </td>
       <td>
        2.479
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350320 ARARAQUARA
       </td>
       <td>
        165.210
       </td>
       <td>
        180.910
       </td>
       <td>
        206.560
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350330 ARARAS
       </td>
       <td>
        86.669
       </td>
       <td>
        103.145
       </td>
       <td>
        117.774
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350335 ARCO-IRIS
       </td>
       <td>
        -
       </td>
       <td>
        2.155
       </td>
       <td>
        1.921
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350340 AREALVA
       </td>
       <td>
        6.828
       </td>
       <td>
        7.212
       </td>
       <td>
        7.818
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350350 AREIAS
       </td>
       <td>
        3.258
       </td>
       <td>
        3.537
       </td>
       <td>
        3.644
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350360 AREIOPOLIS
       </td>
       <td>
        9.953
       </td>
       <td>
        10.283
       </td>
       <td>
        10.553
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350370 ARIRANHA
       </td>
       <td>
        5.838
       </td>
       <td>
        7.456
       </td>
       <td>
        8.530
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350380 ARTUR NOGUEIRA
       </td>
       <td>
        27.693
       </td>
       <td>
        32.996
       </td>
       <td>
        44.102
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350390 ARUJA
       </td>
       <td>
        37.292
       </td>
       <td>
        58.391
       </td>
       <td>
        74.608
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350395 ASPASIA
       </td>
       <td>
        -
       </td>
       <td>
        1.855
       </td>
       <td>
        1.808
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350400 ASSIS
       </td>
       <td>
        84.808
       </td>
       <td>
        86.170
       </td>
       <td>
        93.109
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350410 ATIBAIA
       </td>
       <td>
        85.396
       </td>
       <td>
        109.986
       </td>
       <td>
        125.429
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350420 AURIFLAMA
       </td>
       <td>
        12.685
       </td>
       <td>
        13.465
       </td>
       <td>
        14.142
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350430 AVAI
       </td>
       <td>
        4.584
       </td>
       <td>
        4.477
       </td>
       <td>
        4.913
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350440 AVANHANDAVA
       </td>
       <td>
        7.965
       </td>
       <td>
        8.829
       </td>
       <td>
        10.125
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350450 AVARE
       </td>
       <td>
        59.910
       </td>
       <td>
        74.212
       </td>
       <td>
        80.874
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350460 BADY BASSITT
       </td>
       <td>
        5.711
       </td>
       <td>
        11.528
       </td>
       <td>
        14.587
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350470 BALBINOS
       </td>
       <td>
        1.200
       </td>
       <td>
        1.313
       </td>
       <td>
        1.357
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350480 BALSAMO
       </td>
       <td>
        6.769
       </td>
       <td>
        7.334
       </td>
       <td>
        8.149
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350490 BANANAL
       </td>
       <td>
        11.231
       </td>
       <td>
        9.625
       </td>
       <td>
        10.140
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350500 BARAO DE ANTONINA
       </td>
       <td>
        3.026
       </td>
       <td>
        2.759
       </td>
       <td>
        3.108
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350510 BARBOSA
       </td>
       <td>
        5.357
       </td>
       <td>
        5.829
       </td>
       <td>
        6.452
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350520 BARIRI
       </td>
       <td>
        24.427
       </td>
       <td>
        28.107
       </td>
       <td>
        31.457
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350530 BARRA BONITA
       </td>
       <td>
        30.626
       </td>
       <td>
        35.330
       </td>
       <td>
        35.147
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350535 BARRA DO CHAPEU
       </td>
       <td>
        -
       </td>
       <td>
        4.827
       </td>
       <td>
        5.242
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350540 BARRA DO TURVO
       </td>
       <td>
        6.701
       </td>
       <td>
        7.849
       </td>
       <td>
        7.650
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350550 BARRETOS
       </td>
       <td>
        94.518
       </td>
       <td>
        103.037
       </td>
       <td>
        111.534
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350560 BARRINHA
       </td>
       <td>
        18.785
       </td>
       <td>
        24.134
       </td>
       <td>
        28.442
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350570 BARUERI
       </td>
       <td>
        129.582
       </td>
       <td>
        207.603
       </td>
       <td>
        240.046
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350580 BASTOS
       </td>
       <td>
        19.060
       </td>
       <td>
        20.509
       </td>
       <td>
        20.407
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350590 BATATAIS
       </td>
       <td>
        43.545
       </td>
       <td>
        50.765
       </td>
       <td>
        56.202
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350600 BAURU
       </td>
       <td>
        257.229
       </td>
       <td>
        312.112
       </td>
       <td>
        339.339
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350610 BEBEDOURO
       </td>
       <td>
        67.130
       </td>
       <td>
        74.431
       </td>
       <td>
        74.730
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350620 BENTO DE ABREU
       </td>
       <td>
        2.393
       </td>
       <td>
        2.388
       </td>
       <td>
        2.674
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350630 BERNARDINO DE CAMPOS
       </td>
       <td>
        9.963
       </td>
       <td>
        10.620
       </td>
       <td>
        10.702
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350635 BERTIOGA
       </td>
       <td>
        -
       </td>
       <td>
        29.520
       </td>
       <td>
        47.304
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350640 BILAC
       </td>
       <td>
        5.396
       </td>
       <td>
        6.021
       </td>
       <td>
        7.024
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350650 BIRIGUI
       </td>
       <td>
        74.516
       </td>
       <td>
        94.054
       </td>
       <td>
        108.291
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350660 BIRITIBA-MIRIM
       </td>
       <td>
        17.762
       </td>
       <td>
        24.393
       </td>
       <td>
        28.515
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350670 BOA ESPERANCA DO SUL
       </td>
       <td>
        11.845
       </td>
       <td>
        12.500
       </td>
       <td>
        13.607
       </td>
      </tr>
      <tr align="right">
       <td align="LEFT">
        350680 BOCAINA
       </td>
       <td>

### Método find e find_all

Uma das principais utilidades de BeautifulSoup é encontrar elementos HTML facilmente, através do método `.find(tag)` ou `.find_all(tag)`, em que a `tag` é qualquer uma das disponíveis por HTML, seguem como exemplos:

- Parágrafos, de tag 'p'


```
soup.find('p') # Encontra o primeiro parágrafo da variável soup
soup.find_all('p') # Encontra todos parágrafos da variável soup
```

In [ ]:
soup.find_all('p') # Encontra todos parágrafos, e retorna uma lista

[<p>DATASUS<span>  Tecnologia da Informação a Serviço do SUS<a alt="MS/SE/Datasus" href="http://www.datasus.gov.br" title="MS/SE/Datasus"></a></span></p>,
 <p></p>,
 <p>DATASUS</p>,
 <p align="left">Legenda:</p>,
 <p>
  </p>,
 <p>
 </p>]



- Links, de tag 'a'

```
soup.find('a') # Encontra o primeiro link da variável soup
soup.find_all('a') # Encontra todos links da variável soup
```

In [ ]:
soup.find('a') # Encontra o primeiro link

<a href="http://www.saude.gov.br" target="_blank">
            <img alt="Ministério da Saúde" height="21" id="img1" src="http://www.datasus.gov.br/gifs/principal_r1_c1_res.gif"/>
         </a>

O método `soup.find_all()` retorna um set iterável, logo é possível pegar um link específico:

In [ ]:
soup.find_all('a')[2] # Pega o 3° link no documento HTML.

Note que também é possível extrair o texto:

In [ ]:
soup.find('p').text # Extrai o texto do primeiro parágrafo

'DATASUS\xa0\xa0Tecnologia da Informação a Serviço do SUS'

#### Tabelas

Tabelas também podem ser descobertas pelo método .find(), mas elas normalmente precisam de um pouco de tratamento para serem utilizadas. A tag de tabelas é "table":

In [ ]:
tabela = soup.find('table') # Encontra a primeira tabela

O pandas possui um método para diretamente ler um HTML, `pd.read_html()`. Porém, ele só consegue ler do tipo `StringIO` (em versões mais antigas ele consegue ler HTML literal), o que nossa tabela não é:

In [ ]:
type(tabela) # Mostra o tipo que soup.find(...) traz

bs4.element.Tag

Mas, para modificar, podemos simplesmente encodifica-la:

In [ ]:
tabela_encoded = tabela.encode('utf-8') # Encodifica o HTML em utf-8
df = pd.read_html(tabela_encoded) # Lê todas tabelas do HTML
df[0] # O método retorna uma lista, pois espera que hajam várias tabelas. Pegamos o primeiro elemento da lista.

    Abastecimento de Ã¡gua - SÃ£o Paulo Moradores por Ano segundo MunicÃ­pio PerÃ­odo: 1991, 2000, 2010  \
                                                                                             MunicÃ­pio
0                                                TOTAL
1                                    350010 ADAMANTINA
2                                        350020 ADOLFO
3                                         350030 AGUAI
4                                350040 AGUAS DA PRATA
..                                                 ...
642                                 355710 VOTUPORANGA
643                                    355715 ZACARIAS
644                                   355720 CHAVANTES
645                                355730 ESTIVA GERBI
646  Fonte: IBGE - Censos DemogrÃ¡ficos de 1991, 20...

                                                        \
                                                  1991
0                                           31.284.067
1                                               31.893
2                                                3.271
3                                               23.260
4                                                6.616
..                                                 ...
642                                             65.834
643                                                  -
644                                             14.088
645                                                  -
646  Fonte: IBGE - Censos DemogrÃ¡ficos de 1991, 20...

                                                        \
                                                  2000
0                                           36.713.804
1                                               33.150
2                                                3.677
3                                               27.983
4                                                7.047
..                                                 ...
642                                             75.401
643                                              1.947
644                                             12.134
645                                              8.841
646  Fonte: IBGE - Censos DemogrÃ¡ficos de 1991, 20...


                                                  2010
0                                           40.943.200
1                                               33.471
2                                                3.556
3                                               32.016
4                                                7.503
..                                                 ...
642                                             84.488
643                                              2.335
644                                             12.053
645                                              9.996
646  Fonte: IBGE - Censos DemogrÃ¡ficos de 1991, 20...

[647 rows x 4 columns]

#### Exemplo de HTMLs com múltiplas tabelas

Podemos também especificar alguma restrição com um dicionário com outras chaves HTML, para quando há mais de uma tabela:

In [ ]:
# Abaixo está um HTML com duas tabelas, tente mudar a classe e ID das tabelas para ver o que ocorre.
html_exemplo = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test Tables</title>
</head>
<body>

    <table class="Notas">
        <tr>
            <th>Nome</th>
            <th>Nota</th>
        </tr>
        <tr>
            <td>Alice</td>
            <td>9.9</td>
        </tr>
        <tr>
            <td>Heitor</td>
            <td>9.8</td>
        </tr>
        <tr>
            <td>Victor</td>
            <td>9.7</td>
        </tr>
    </table>

    <table id="id_qualquer">
        <tr>
            <th>Animal</th>
            <th>População</th>
        </tr>
        <tr>
            <td>Unicórnio</td>
            <td>27</td>
        </tr>
        <tr>
            <td>Dragão</td>
            <td>13</td>
        </tr>
        <tr>
            <td>Pé-grande</td>
            <td>1</td>
        </tr>
    </table>

</body>
</html>
"""

In [ ]:
soup_exemplo = BeautifulSoup(html_exemplo,'html5lib') # Salva o html processado na variável

tabela_classe = soup_exemplo.find('table', # Encontra a primeira tabela
 {'class':'Notas'}) # Cuja class = Notas


tabela_id = soup_exemplo.find('table', # Encontra a primeira tabela
 {'id':'id_qualquer'}) # Cujo id = id_qualquer

print(tabela_id.prettify()) # Imprime a tabela_id.

<table id="id_qualquer">
 <tbody>
  <tr>
   <th>
    Animal
   </th>
   <th>
    População
   </th>
  </tr>
  <tr>
   <td>
    Unicórnio
   </td>
   <td>
    27
   </td>
  </tr>
  <tr>
   <td>
    Dragão
   </td>
   <td>
    13
   </td>
  </tr>
  <tr>
   <td>
    Pé-grande
   </td>
   <td>
    1
   </td>
  </tr>
 </tbody>
</table>

Também pode-se apenas ler todas a tabelas diretamente, e selecionar por slicing:

In [ ]:
dfs = pd.read_html(html_exemplo.encode('utf-8')) # Lê o HTML já encodificado, retorna uma lista

df_id = dfs[1] # Pega a segunda tabela da lista
df_class = dfs[0] # Pega a primeira tabela da lista
df_id

      Animal  População
0  Unicórnio         27
1     Dragão         13
2  Pé-grande          1

# Exercícios

## Exercício 1
Extraia os dados do link abaixo. E monte um pandas dataframe.  
*Dica: para URLs mais simples, é possível usar pandas diretamente no url.*  
*Dica 2: caso alguns símbolos não estejam aparecendo corretamente, tente usar outra encodificação, como 'utf-8'*

In [ ]:
url = "https://www.loq.eel.usp.br/docentes"

## Exercício 2

Usando a API do inmet, pegue os dados horários desde o começo do ano até hoje. Para uma estação qualquer.  
Lembrando:  
- Lista de estações
- Para ter a data de hoje já formatada, use o código abaixo:

In [ ]:
from datetime import date

In [ ]:
data_hoje = date.today().strftime('%Y-%m-%d')
data_hoje

'2025-03-31'

## Exercício 3

Faça uma DataFrame siga as seguintes etapas:
- Peça ao usuário duas datas ;
- Use a data de hoje ;
- Pegue dados horários de TODAS estações às 00h:00m, para ambas;
- Crie uma DataFrame com ambas concatenadas;
- Remova os NaNs.

In [ ]:
from datetime import date
data_hoje = date.today().strftime('%Y-%m-%d')
url_base = ' https://apitempo.inmet.gov.br/token/estacao/dados'
data_a = ...